import React from "react";
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';

type Props = {};

function NotFound({}: Props) {
  return (
    <div className="flex flex-col min-h-[70vh] w-full justify-center items-center gap-12">
      <div className="flex flex-col items-center justify-center text-center space-y-8">
        {/* Big App Logo */}
        <div className="flex justify-center">
          <Avatar className="h-32 w-32 rounded-2xl">
            <AvatarImage src="/vivid.png" alt="ai-presentation-logo" />
            <AvatarFallback className="rounded-2xl text-4xl font-semibold">VI</AvatarFallback>
          </Avatar>
        </div>

        {/* Text Content */}
        <div className="space-y-4">
          <p className="text-3xl font-semibold text-primary">
            Nothing to see here
          </p>
          <p className="text-base font-normal text-secondary">
            So here is a random image generated by{" "}
            <span className="text-vivid">Creative AI</span>
          </p>
        </div>
      </div>
    </div>
  );
}

export default NotFound;